### ISSUE TITLE
在 ConST/scripts/train_en2x.sh 里的 arch 是 xstnet_base

### ISSUE THREAD

**Issue by JuneAndJuly** [ReneeYe/ConST#1]
请问直接运行ConST/scripts/train_en2x.sh这个脚本得到的结果是xstnet的结果还是const的结果

**Comment by ReneeYe** [comment]
@JuneAndJuly hi，train_en2x.sh 的arg中的criterion是multi_task_cross_entropy_**with_contrastive**_with_extra_MT 哦～，所以是ConST。如果想看XSTNet，可以把contrastive-weight 设置为0，也可以～（就是略不优雅hhhh，优雅一点，可以自己改写一个multi_task_cross_entropy criterion, hhhh）

**Comment by JuneAndJuly** [comment]
感谢回复~
