### ISSUE TITLE
Extra MT Data

### ISSUE THREAD

**Issue by ethanyklei** [ReneeYe/ConST#2]
Hi, you have restricted in the script `download_wmt.sh` that only `en-ro` parallel data comes from wmt16 version, however you wrote in you paper that `en-de` and `en-ru` parallel data also come from wmt16. Is there something wrong in your paper or your script?

```
# download_wmt.sh
if [[ $version == "wmt16" && $target != "ro" ]] || [[ $version != "wmt16" && $target == "ro" ]]; then
    echo "--wmt16 if and only if target is ro"
    exit
fi

```

**Comment by ReneeYe** [comment]
@codeboy311 Good finding! **The external dataset in the paper is correct, WMT16 for en-de, etc..** For the experiment, I used the long-existing WMT data on the server(or HDFS in my company) directly and didn't pay much attention to the problem you mentioned.😂 The script is just for downloading WMT, which I mindlessly copied from another repo.😛  

BTW, the difference between WMT16 and WMT14 is probably not that big, these data are used to better pre-train the shared transformer enc-dec module. Of course, you can also use the newer WMT21 data, the scale of En-De is much larger, and I guess that maybe with better MT pre-training, the ST will be better too. 🤔
