### ISSUE TITLE
Reproduce experiments with external MT data

### ISSUE THREAD

**Issue by lyc2001** [ReneeYe/ConST#7]
Hello,

Thank you very much for sharing your work!
I have followed your script to run the experiments on the En->De ST. I got a BLEU score of 25.31 without using external MT data. With external MT data used, I got 25.82, which is lower than 28.3 in your paper.
I'm wondering if a pre-trained MT model was perhaps utilized to achieve the 28.3 score? Or is there anything else that I might have missed in the process? Any suggestions or guidance you can offer would be greatly appreciated.

Thank you in advanced!

**Comment by ReneeYe** [comment]
> Hello,
> 
> Thank you very much for sharing your work! I have followed your script to run the experiments on the En->De ST. I got a BLEU score of 25.31 without using external MT data. With external MT data used, I got 25.82, which is lower than 28.3 in your paper. I'm wondering if a pre-trained MT model was perhaps utilized to achieve the 28.3 score? Or is there anything else that I might have missed in the process? Any suggestions or guidance you can offer would be greatly appreciated.
> 
> Thank you in advanced!

Really sorry for the late reply! ;( 
**Yes, you need to first pretrain the encoder-decoder model with external MT data (ie WMT16 data).** 
The data download and preparation code for pre-training with MT data are under ConST/scripts. 
For MT training, you can refer to the example in fairseq, and the corresponding task is also in the ``fairseq/tasks/translation_with_langtag.py``.
After the trained MT checkpoint (it is also recommended to do checkpoint average. suppose we save at ``./checkpoints/MTpretrain/checkpoint.best_avg.pt``) then train the speech translation model, refer to script/train_en2x.sh
Remember to add following args:
```
--finetune-from-model ./checkpoints/MTpretrain/checkpoint.best_avg.pt \
--find-unused-parameters 
```
